
import axios from 'axios'


export async function search(query, accessToken){
	const recommendationLink = [
		"https://api.spotify.com/v1/search",
		`?authorization=${accessToken}`,
		`&q=${query}`,
		`&type=track`,
		`&offset=0`,
	].join('');
	
	const AuthStr = 'Bearer ' + accessToken;
	const res = await axios.get(recommendationLink, { 'headers': { 'Authorization': AuthStr } });
	const resData = res.data;
	return resData['tracks']['items'];
}

export async function getRecommendation(seedSong, sliderValueDict, accessToken, numberPerSeed){
	// const range = 0.1;
	const recommendationLink = [
		"https://api.spotify.com/v1/recommendations",
		`?authorization=${accessToken}`,
		`&seed_tracks=${seedSong.id}`,
		`&limit=${numberPerSeed}`,
		// `&min_danceability=${sliderValueDict['danceability'] - range}`,
		// `&max_danceability=${sliderValueDict['danceability'] + range}`,
		// `&min_energy=${sliderValueDict['energy'] - range}`,
		// `&max_energy=${sliderValueDict['energy'] + range}`,
		// `&min_valence=${sliderValueDict['happiness'] - range}`,
		// `&max_valence=${sliderValueDict['happiness'] + range}`,
		// `&min_popularity=${sliderValueDict['popularity'] - (2*range*10)}`,
		// `&max_popularity=${sliderValueDict['popularity'] + (2*range*10)}`,
		`&target_danceability=${sliderValueDict['danceability']}`,
		`&target_energy=${sliderValueDict['energy']}`,
		`&target_valence=${sliderValueDict['happiness']}`,
		`&target_popularity=${sliderValueDict['popularity']}`,
	
	].join('');
	
	const AuthStr = 'Bearer ' + accessToken;
	const res = await axios.get(recommendationLink, { 'headers': { 'Authorization': AuthStr } })
	const resData = res.data;
	let tracks =  resData['tracks'];
	let recommendations = [];
	for (let i = 0; i < tracks.length; i++){
		let audioFeatures = await getAudioFeatures(tracks[i], accessToken)
		let seedInfo = {
			seedId: seedSong.id,
			seedTitle: seedSong.title,
			seedArtist:seedSong.artist,
			seedAlbum:seedSong.album,
			seedPreview_url: seedSong.preview_url
		};
		let recommendation = Object.assign(tracks[i], audioFeatures, seedInfo)
		recommendations = [...recommendations, recommendation]
	}
	return recommendations
}

export async function getAudioFeatures(song, accessToken){
	const idSong = song['id'];
	const request = [
		"https://api.spotify.com/v1/audio-features/",
		`${idSong}`,
	].join('');
	const AuthStr = 'Bearer ' + accessToken;
	const res = await axios.get(request, { 'headers': { 'Authorization': AuthStr } });
	const resData = res.data;
	return resData
}

export async function getTopSong(accessToken, version) {
	//todo test with 'empty' account
	const topLink = [
		"https://api.spotify.com/v1/me/top/tracks"
	].join('');
	const AuthStr = 'Bearer ' + accessToken;
	const res = await axios.get(topLink, { 'headers': { 'Authorization': AuthStr } });
	const resData = res.data;
	const topSongs = resData.items;
	if (topSongs.length > 0){
		let added = 0;
		let index = 0;
		let topSong = null;
		let topSongList = [];
		while (added < 2 || index === 20){
			if (topSongs[index]['preview_url'] !== null){
				let audioFeatures = await getAudioFeatures(topSongs[index], accessToken)
				topSong = Object.assign(topSongs[index], audioFeatures);
				topSongList.push(topSong)
				added += 1
			}
			index += 1;
		}
		const indexTopSong = version -1;
		return topSongList[indexTopSong]
		
	}
	else{
		const topSongList = [
			{
				"album": {
					"album_type": "SINGLE",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/3YQKmKGau1PzlVlkL1iodx"
							},
							"href": "https://api.spotify.com/v1/artists/3YQKmKGau1PzlVlkL1iodx",
							"id": "3YQKmKGau1PzlVlkL1iodx",
							"name": "Twenty One Pilots",
							"type": "artist",
							"uri": "spotify:artist:3YQKmKGau1PzlVlkL1iodx"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/3J8W9AOjQhnBLCX33m3atT"
					},
					"href": "https://api.spotify.com/v1/albums/3J8W9AOjQhnBLCX33m3atT",
					"id": "3J8W9AOjQhnBLCX33m3atT",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b2732ca3ba8f334ca5a5f0312efb",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e022ca3ba8f334ca5a5f0312efb",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d000048512ca3ba8f334ca5a5f0312efb",
							"width": 64
						}
					],
					"name": "Heathens",
					"release_date": "2016-06-16",
					"release_date_precision": "day",
					"total_tracks": 1,
					"type": "album",
					"uri": "spotify:album:3J8W9AOjQhnBLCX33m3atT"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/3YQKmKGau1PzlVlkL1iodx"
						},
						"href": "https://api.spotify.com/v1/artists/3YQKmKGau1PzlVlkL1iodx",
						"id": "3YQKmKGau1PzlVlkL1iodx",
						"name": "Twenty One Pilots",
						"type": "artist",
						"uri": "spotify:artist:3YQKmKGau1PzlVlkL1iodx"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 195920,
				"explicit": false,
				"external_ids": {
					"isrc": "USAT21601930"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/6i0V12jOa3mr6uu4WYhUBr"
				},
				"href": "https://api.spotify.com/v1/tracks/6i0V12jOa3mr6uu4WYhUBr",
				"id": "6i0V12jOa3mr6uu4WYhUBr",
				"is_local": false,
				"name": "Heathens",
				"popularity": 81,
				"preview_url": "https://p.scdn.co/mp3-preview/cd5173acb956b9f442c67bafd2ec637a898ab172?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 1,
				"type": "audio_features",
				"uri": "spotify:track:6i0V12jOa3mr6uu4WYhUBr",
				"danceability": 0.732,
				"energy": 0.396,
				"key": 4,
				"loudness": -9.348,
				"mode": 0,
				"speechiness": 0.0286,
				"acousticness": 0.0841,
				"instrumentalness": 0.0000358,
				"liveness": 0.105,
				"valence": 0.548,
				"tempo": 90.024,
				"track_href": "https://api.spotify.com/v1/tracks/6i0V12jOa3mr6uu4WYhUBr",
				"analysis_url": "https://api.spotify.com/v1/audio-analysis/6i0V12jOa3mr6uu4WYhUBr",
				"time_signature": 4
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz"
							},
							"href": "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
							"id": "6XyY86QOPPrYVGvF9ch6wz",
							"name": "Linkin Park",
							"type": "artist",
							"uri": "spotify:artist:6XyY86QOPPrYVGvF9ch6wz"
						}
					],
					"available_markets": [
						"AD",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IS",
						"IT",
						"JP",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"PA",
						"PE",
						"PH",
						"PL",
						"PT",
						"PY",
						"RO",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/2tlTBLz2w52rpGCLBGyGw6"
					},
					"href": "https://api.spotify.com/v1/albums/2tlTBLz2w52rpGCLBGyGw6",
					"id": "2tlTBLz2w52rpGCLBGyGw6",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b27346e207de66ba06422897f769",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e0246e207de66ba06422897f769",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d0000485146e207de66ba06422897f769",
							"width": 64
						}
					],
					"name": "Minutes to Midnight",
					"release_date": "2007-05-14",
					"release_date_precision": "day",
					"total_tracks": 12,
					"type": "album",
					"uri": "spotify:album:2tlTBLz2w52rpGCLBGyGw6"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz"
						},
						"href": "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
						"id": "6XyY86QOPPrYVGvF9ch6wz",
						"name": "Linkin Park",
						"type": "artist",
						"uri": "spotify:artist:6XyY86QOPPrYVGvF9ch6wz"
					}
				],
				"available_markets": [
					"AD",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IS",
					"IT",
					"JP",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"PA",
					"PE",
					"PH",
					"PL",
					"PT",
					"PY",
					"RO",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 166373,
				"explicit": true,
				"external_ids": {
					"isrc": "USWB10701213"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/0UFDKFqW2oGspYeYqo9wjA"
				},
				"href": "https://api.spotify.com/v1/tracks/0UFDKFqW2oGspYeYqo9wjA",
				"id": "0UFDKFqW2oGspYeYqo9wjA",
				"is_local": false,
				"name": "Bleed It Out",
				"popularity": 73,
				"preview_url": "https://p.scdn.co/mp3-preview/04212367c04f73a6a81217b3cb81ad70288af8a5?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 4,
				"type": "audio_features",
				"uri": "spotify:track:0UFDKFqW2oGspYeYqo9wjA",
				"danceability": 0.529,
				"energy": 0.967,
				"key": 1,
				"loudness": -3.647,
				"mode": 0,
				"speechiness": 0.0508,
				"acousticness": 0.114,
				"instrumentalness": 0,
				"liveness": 0.61,
				"valence": 0.596,
				"tempo": 140.127,
				"track_href": "https://api.spotify.com/v1/tracks/0UFDKFqW2oGspYeYqo9wjA",
				"analysis_url": "https://api.spotify.com/v1/audio-analysis/0UFDKFqW2oGspYeYqo9wjA",
				"time_signature": 4
			},
			{
				"album": {
					"album_type": "COMPILATION",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
							},
							"href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
							"id": "0LyfQWJT6nXafLPZqxe9Of",
							"name": "Various Artists",
							"type": "artist",
							"uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
						}
					],
					"available_markets": [
						"AE",
						"AU",
						"BE",
						"BG",
						"BH",
						"BR",
						"CH",
						"CY",
						"CZ",
						"DE",
						"DK",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"HK",
						"HU",
						"ID",
						"IE",
						"IL",
						"IS",
						"JO",
						"JP",
						"LB",
						"LT",
						"LU",
						"LV",
						"MT",
						"MY",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PH",
						"PT",
						"QA",
						"SA",
						"SE",
						"SG",
						"SK",
						"TN",
						"TR",
						"TW",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/5SwpV7g0iey70Ux6xeHKw0"
					},
					"href": "https://api.spotify.com/v1/albums/5SwpV7g0iey70Ux6xeHKw0",
					"id": "5SwpV7g0iey70Ux6xeHKw0",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273705c94cf82e11346e23ae83b",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02705c94cf82e11346e23ae83b",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851705c94cf82e11346e23ae83b",
							"width": 64
						}
					],
					"name": "Hits For Børn 2",
					"release_date": "2005-01-01",
					"release_date_precision": "day",
					"total_tracks": 12,
					"type": "album",
					"uri": "spotify:album:5SwpV7g0iey70Ux6xeHKw0"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/2UOx6w3eHpPKc3RBnNV3Rl"
						},
						"href": "https://api.spotify.com/v1/artists/2UOx6w3eHpPKc3RBnNV3Rl",
						"id": "2UOx6w3eHpPKc3RBnNV3Rl",
						"name": "Safri Duo",
						"type": "artist",
						"uri": "spotify:artist:2UOx6w3eHpPKc3RBnNV3Rl"
					}
				],
				"available_markets": [
					"AE",
					"AU",
					"BE",
					"BG",
					"BH",
					"BR",
					"CH",
					"CY",
					"CZ",
					"DE",
					"DK",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"HK",
					"HU",
					"ID",
					"IE",
					"IL",
					"IS",
					"JO",
					"JP",
					"LB",
					"LT",
					"LU",
					"LV",
					"MT",
					"MY",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PH",
					"PT",
					"QA",
					"SA",
					"SE",
					"SG",
					"SK",
					"TN",
					"TR",
					"TW",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 196560,
				"explicit": false,
				"external_ids": {
					"isrc": "DKBKA0001601"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/2MDdh4rbNNBiy8l6XgI6E9"
				},
				"href": "https://api.spotify.com/v1/tracks/2MDdh4rbNNBiy8l6XgI6E9",
				"id": "2MDdh4rbNNBiy8l6XgI6E9",
				"is_local": false,
				"name": "Played-A-Live (The Bongo Song) - Radio Edit",
				"popularity": 58,
				"preview_url": null,
				"track_number": 1,
				"type": "track",
				"uri": "spotify:track:2MDdh4rbNNBiy8l6XgI6E9"
			},
			{
				"album": {
					"album_type": "COMPILATION",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
							},
							"href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
							"id": "0LyfQWJT6nXafLPZqxe9Of",
							"name": "Various Artists",
							"type": "artist",
							"uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AT",
						"BE",
						"BG",
						"BH",
						"CH",
						"CY",
						"CZ",
						"DE",
						"DK",
						"EE",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"HU",
						"IE",
						"IL",
						"IS",
						"IT",
						"JO",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MC",
						"MT",
						"NL",
						"NO",
						"OM",
						"PL",
						"PT",
						"QA",
						"RO",
						"SA",
						"SE",
						"SK",
						"TR",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/46co3YFtDUWwq1DiazleHP"
					},
					"href": "https://api.spotify.com/v1/albums/46co3YFtDUWwq1DiazleHP",
					"id": "46co3YFtDUWwq1DiazleHP",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b27397de5f41f1bda315d128e086",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e0297de5f41f1bda315d128e086",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d0000485197de5f41f1bda315d128e086",
							"width": 64
						}
					],
					"name": "Pirates Of The Caribbean Original Soundtrack",
					"release_date": "2003-01-01",
					"release_date_precision": "day",
					"total_tracks": 15,
					"type": "album",
					"uri": "spotify:album:46co3YFtDUWwq1DiazleHP"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/03GruNQP8X25PCoWzdvIGZ"
						},
						"href": "https://api.spotify.com/v1/artists/03GruNQP8X25PCoWzdvIGZ",
						"id": "03GruNQP8X25PCoWzdvIGZ",
						"name": "Klaus Badelt",
						"type": "artist",
						"uri": "spotify:artist:03GruNQP8X25PCoWzdvIGZ"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AT",
					"BE",
					"BG",
					"BH",
					"CH",
					"CY",
					"CZ",
					"DE",
					"DK",
					"EE",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"HU",
					"IE",
					"IL",
					"IS",
					"IT",
					"JO",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MC",
					"MT",
					"NL",
					"NO",
					"OM",
					"PL",
					"PT",
					"QA",
					"RO",
					"SA",
					"SE",
					"SK",
					"TR",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 136280,
				"explicit": false,
				"external_ids": {
					"isrc": "USWD10321329"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/6r6wolzRxCSNuY7arMNwMe"
				},
				"href": "https://api.spotify.com/v1/tracks/6r6wolzRxCSNuY7arMNwMe",
				"id": "6r6wolzRxCSNuY7arMNwMe",
				"is_local": false,
				"name": "The Black Pearl",
				"popularity": 50,
				"preview_url": null,
				"track_number": 3,
				"type": "track",
				"uri": "spotify:track:6r6wolzRxCSNuY7arMNwMe"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY"
							},
							"href": "https://api.spotify.com/v1/artists/4dpARuHxo51G3z768sgnrY",
							"id": "4dpARuHxo51G3z768sgnrY",
							"name": "Adele",
							"type": "artist",
							"uri": "spotify:artist:4dpARuHxo51G3z768sgnrY"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"CA",
						"CH",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DZ",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"HK",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MY",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PH",
						"PL",
						"PS",
						"PT",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"TH",
						"TN",
						"TR",
						"TW",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/7n3QJc7TBOxXtlYh4Ssll8"
					},
					"href": "https://api.spotify.com/v1/albums/7n3QJc7TBOxXtlYh4Ssll8",
					"id": "7n3QJc7TBOxXtlYh4Ssll8",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273ba764098164f221484bcc309",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02ba764098164f221484bcc309",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851ba764098164f221484bcc309",
							"width": 64
						}
					],
					"name": "21",
					"release_date": "2011-01-19",
					"release_date_precision": "day",
					"total_tracks": 11,
					"type": "album",
					"uri": "spotify:album:7n3QJc7TBOxXtlYh4Ssll8"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY"
						},
						"href": "https://api.spotify.com/v1/artists/4dpARuHxo51G3z768sgnrY",
						"id": "4dpARuHxo51G3z768sgnrY",
						"name": "Adele",
						"type": "artist",
						"uri": "spotify:artist:4dpARuHxo51G3z768sgnrY"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"CA",
					"CH",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DZ",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"HK",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MY",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PH",
					"PL",
					"PS",
					"PT",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"TH",
					"TN",
					"TR",
					"TW",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 228093,
				"explicit": true,
				"external_ids": {
					"isrc": "GBBKS1000335"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/1eq1wUnLVLg4pdEfx9kajC"
				},
				"href": "https://api.spotify.com/v1/tracks/1eq1wUnLVLg4pdEfx9kajC",
				"id": "1eq1wUnLVLg4pdEfx9kajC",
				"is_local": false,
				"name": "Rolling in the Deep",
				"popularity": 76,
				"preview_url": "https://p.scdn.co/mp3-preview/b2ba47ab9af2b4cd08a04e45b94803bd076c209d?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 1,
				"type": "track",
				"uri": "spotify:track:1eq1wUnLVLg4pdEfx9kajC"
			},
			{
				"album": {
					"album_type": "SINGLE",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/7oPftvlwr6VrsViSDV7fJY"
							},
							"href": "https://api.spotify.com/v1/artists/7oPftvlwr6VrsViSDV7fJY",
							"id": "7oPftvlwr6VrsViSDV7fJY",
							"name": "Green Day",
							"type": "artist",
							"uri": "spotify:artist:7oPftvlwr6VrsViSDV7fJY"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AT",
						"BE",
						"BG",
						"BH",
						"CA",
						"CH",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DZ",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GR",
						"HU",
						"IE",
						"IL",
						"IS",
						"IT",
						"JO",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"NL",
						"NO",
						"OM",
						"PL",
						"PT",
						"QA",
						"RO",
						"SA",
						"SE",
						"SK",
						"TN",
						"TR",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/2sIWM1FzNqLCccNwXuC4SA"
					},
					"href": "https://api.spotify.com/v1/albums/2sIWM1FzNqLCccNwXuC4SA",
					"id": "2sIWM1FzNqLCccNwXuC4SA",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b27397e3ca5aecb464f021c601d5",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e0297e3ca5aecb464f021c601d5",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d0000485197e3ca5aecb464f021c601d5",
							"width": 64
						}
					],
					"name": "Boulevard of Broken Dreams",
					"release_date": "2004",
					"release_date_precision": "year",
					"total_tracks": 1,
					"type": "album",
					"uri": "spotify:album:2sIWM1FzNqLCccNwXuC4SA"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/7oPftvlwr6VrsViSDV7fJY"
						},
						"href": "https://api.spotify.com/v1/artists/7oPftvlwr6VrsViSDV7fJY",
						"id": "7oPftvlwr6VrsViSDV7fJY",
						"name": "Green Day",
						"type": "artist",
						"uri": "spotify:artist:7oPftvlwr6VrsViSDV7fJY"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AT",
					"BE",
					"BG",
					"BH",
					"CA",
					"CH",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DZ",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GR",
					"HU",
					"IE",
					"IL",
					"IS",
					"IT",
					"JO",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"NL",
					"NO",
					"OM",
					"PL",
					"PT",
					"QA",
					"RO",
					"SA",
					"SE",
					"SK",
					"TN",
					"TR",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 261266,
				"explicit": true,
				"external_ids": {
					"isrc": "USRE10401426"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/1hwJKpe0BPUsq6UUrwBWTw"
				},
				"href": "https://api.spotify.com/v1/tracks/1hwJKpe0BPUsq6UUrwBWTw",
				"id": "1hwJKpe0BPUsq6UUrwBWTw",
				"is_local": false,
				"name": "Boulevard of Broken Dreams",
				"popularity": 72,
				"preview_url": "https://p.scdn.co/mp3-preview/439804a8cc76ae7d380ae25d86ad9a4b314eae98?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 1,
				"type": "track",
				"uri": "spotify:track:1hwJKpe0BPUsq6UUrwBWTw"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0RqtSIYZmd4fiBKVFqyIqD"
							},
							"href": "https://api.spotify.com/v1/artists/0RqtSIYZmd4fiBKVFqyIqD",
							"id": "0RqtSIYZmd4fiBKVFqyIqD",
							"name": "Thirty Seconds To Mars",
							"type": "artist",
							"uri": "spotify:artist:0RqtSIYZmd4fiBKVFqyIqD"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/5nI4Eo1vWUWXzeT4WrzTGL"
					},
					"href": "https://api.spotify.com/v1/albums/5nI4Eo1vWUWXzeT4WrzTGL",
					"id": "5nI4Eo1vWUWXzeT4WrzTGL",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273dc71afe98ba69bee55dddf4e",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02dc71afe98ba69bee55dddf4e",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851dc71afe98ba69bee55dddf4e",
							"width": 64
						}
					],
					"name": "This Is War (Deluxe)",
					"release_date": "2009",
					"release_date_precision": "year",
					"total_tracks": 15,
					"type": "album",
					"uri": "spotify:album:5nI4Eo1vWUWXzeT4WrzTGL"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/0RqtSIYZmd4fiBKVFqyIqD"
						},
						"href": "https://api.spotify.com/v1/artists/0RqtSIYZmd4fiBKVFqyIqD",
						"id": "0RqtSIYZmd4fiBKVFqyIqD",
						"name": "Thirty Seconds To Mars",
						"type": "artist",
						"uri": "spotify:artist:0RqtSIYZmd4fiBKVFqyIqD"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 361680,
				"explicit": false,
				"external_ids": {
					"isrc": "GBCAD1001307"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/2728QcZxNHBFTb4gnPsU4X"
				},
				"href": "https://api.spotify.com/v1/tracks/2728QcZxNHBFTb4gnPsU4X",
				"id": "2728QcZxNHBFTb4gnPsU4X",
				"is_local": false,
				"name": "Stronger - Live",
				"popularity": 34,
				"preview_url": null,
				"track_number": 15,
				"type": "track",
				"uri": "spotify:track:2728QcZxNHBFTb4gnPsU4X"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI"
							},
							"href": "https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI",
							"id": "12Chz98pHFMPJEknJQMWvI",
							"name": "Muse",
							"type": "artist",
							"uri": "spotify:artist:12Chz98pHFMPJEknJQMWvI"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/2wart5Qjnvx1fd7LPdQxgJ"
					},
					"href": "https://api.spotify.com/v1/albums/2wart5Qjnvx1fd7LPdQxgJ",
					"id": "2wart5Qjnvx1fd7LPdQxgJ",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273808846f0223d97d5963c420d",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02808846f0223d97d5963c420d",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851808846f0223d97d5963c420d",
							"width": 64
						}
					],
					"name": "Drones",
					"release_date": "2015-06-04",
					"release_date_precision": "day",
					"total_tracks": 12,
					"type": "album",
					"uri": "spotify:album:2wart5Qjnvx1fd7LPdQxgJ"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI"
						},
						"href": "https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI",
						"id": "12Chz98pHFMPJEknJQMWvI",
						"name": "Muse",
						"type": "artist",
						"uri": "spotify:artist:12Chz98pHFMPJEknJQMWvI"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 316717,
				"explicit": true,
				"external_ids": {
					"isrc": "GBAHT1500068"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/383QXk8nb2YrARMUwDdjQS"
				},
				"href": "https://api.spotify.com/v1/tracks/383QXk8nb2YrARMUwDdjQS",
				"id": "383QXk8nb2YrARMUwDdjQS",
				"is_local": false,
				"name": "Psycho",
				"popularity": 69,
				"preview_url": "https://p.scdn.co/mp3-preview/9825aad9fc20222cfd2db3eba32469181b90c8d8?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 3,
				"type": "track",
				"uri": "spotify:track:383QXk8nb2YrARMUwDdjQS"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/6zUiRChNyL3HEezOd1Wjam"
							},
							"href": "https://api.spotify.com/v1/artists/6zUiRChNyL3HEezOd1Wjam",
							"id": "6zUiRChNyL3HEezOd1Wjam",
							"name": "Buraka Som Sistema",
							"type": "artist",
							"uri": "spotify:artist:6zUiRChNyL3HEezOd1Wjam"
						}
					],
					"available_markets": [
						"AD",
						"BE",
						"BG",
						"CY",
						"CZ",
						"DK",
						"EE",
						"ES",
						"FI",
						"FR",
						"GR",
						"HU",
						"IS",
						"IT",
						"LI",
						"LT",
						"LU",
						"LV",
						"MC",
						"MT",
						"NL",
						"NO",
						"PL",
						"RO",
						"SE",
						"SK",
						"TR"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/5wCt1tK0FYXqjvqRNB7nWl"
					},
					"href": "https://api.spotify.com/v1/albums/5wCt1tK0FYXqjvqRNB7nWl",
					"id": "5wCt1tK0FYXqjvqRNB7nWl",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b2730d5ca85c741b052173833088",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e020d5ca85c741b052173833088",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d000048510d5ca85c741b052173833088",
							"width": 64
						}
					],
					"name": "Black Diamond",
					"release_date": "2009-02-08",
					"release_date_precision": "day",
					"total_tracks": 13,
					"type": "album",
					"uri": "spotify:album:5wCt1tK0FYXqjvqRNB7nWl"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/6zUiRChNyL3HEezOd1Wjam"
						},
						"href": "https://api.spotify.com/v1/artists/6zUiRChNyL3HEezOd1Wjam",
						"id": "6zUiRChNyL3HEezOd1Wjam",
						"name": "Buraka Som Sistema",
						"type": "artist",
						"uri": "spotify:artist:6zUiRChNyL3HEezOd1Wjam"
					},
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/5hY9FWUpym7RjAz84ykh8V"
						},
						"href": "https://api.spotify.com/v1/artists/5hY9FWUpym7RjAz84ykh8V",
						"id": "5hY9FWUpym7RjAz84ykh8V",
						"name": "Pongolove",
						"type": "artist",
						"uri": "spotify:artist:5hY9FWUpym7RjAz84ykh8V"
					}
				],
				"available_markets": [
					"AD",
					"BE",
					"BG",
					"CY",
					"CZ",
					"DK",
					"EE",
					"ES",
					"FI",
					"FR",
					"GR",
					"HU",
					"IS",
					"IT",
					"LI",
					"LT",
					"LU",
					"LV",
					"MC",
					"MT",
					"NL",
					"NO",
					"PL",
					"RO",
					"SE",
					"SK",
					"TR"
				],
				"disc_number": 1,
				"duration_ms": 233186,
				"explicit": false,
				"external_ids": {
					"isrc": "PTSM10800033"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/5W3bVIVRmBFbhPUiZrZxQw"
				},
				"href": "https://api.spotify.com/v1/tracks/5W3bVIVRmBFbhPUiZrZxQw",
				"id": "5W3bVIVRmBFbhPUiZrZxQw",
				"is_local": false,
				"name": "Kalemba (Wegue Wegue)",
				"popularity": 42,
				"preview_url": "https://p.scdn.co/mp3-preview/9ab001a7969012b601cb6a1d470bd583905e6f55?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 4,
				"type": "track",
				"uri": "spotify:track:5W3bVIVRmBFbhPUiZrZxQw"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/4RddZ3iHvSpGV4dvATac9X"
							},
							"href": "https://api.spotify.com/v1/artists/4RddZ3iHvSpGV4dvATac9X",
							"id": "4RddZ3iHvSpGV4dvATac9X",
							"name": "Papa Roach",
							"type": "artist",
							"uri": "spotify:artist:4RddZ3iHvSpGV4dvATac9X"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/0BHa0ePkvGAVKymB4FU58m"
					},
					"href": "https://api.spotify.com/v1/albums/0BHa0ePkvGAVKymB4FU58m",
					"id": "0BHa0ePkvGAVKymB4FU58m",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273985bf5ede2fe4a048ee85f28",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02985bf5ede2fe4a048ee85f28",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851985bf5ede2fe4a048ee85f28",
							"width": 64
						}
					],
					"name": "Infest",
					"release_date": "2001-04-25",
					"release_date_precision": "day",
					"total_tracks": 13,
					"type": "album",
					"uri": "spotify:album:0BHa0ePkvGAVKymB4FU58m"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4RddZ3iHvSpGV4dvATac9X"
						},
						"href": "https://api.spotify.com/v1/artists/4RddZ3iHvSpGV4dvATac9X",
						"id": "4RddZ3iHvSpGV4dvATac9X",
						"name": "Papa Roach",
						"type": "artist",
						"uri": "spotify:artist:4RddZ3iHvSpGV4dvATac9X"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 199906,
				"explicit": true,
				"external_ids": {
					"isrc": "USDW10021712"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/5W8YXBz9MTIDyrpYaCg2Ky"
				},
				"href": "https://api.spotify.com/v1/tracks/5W8YXBz9MTIDyrpYaCg2Ky",
				"id": "5W8YXBz9MTIDyrpYaCg2Ky",
				"is_local": false,
				"name": "Last Resort",
				"popularity": 80,
				"preview_url": null,
				"track_number": 2,
				"type": "track",
				"uri": "spotify:track:5W8YXBz9MTIDyrpYaCg2Ky"
			},
			{
				"album": {
					"album_type": "COMPILATION",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/7jy3rLJdDQY21OgRLCZ9sD"
							},
							"href": "https://api.spotify.com/v1/artists/7jy3rLJdDQY21OgRLCZ9sD",
							"id": "7jy3rLJdDQY21OgRLCZ9sD",
							"name": "Foo Fighters",
							"type": "artist",
							"uri": "spotify:artist:7jy3rLJdDQY21OgRLCZ9sD"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/1zCNrbPpz5OLSr6mSpPdKm"
					},
					"href": "https://api.spotify.com/v1/albums/1zCNrbPpz5OLSr6mSpPdKm",
					"id": "1zCNrbPpz5OLSr6mSpPdKm",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273136d7250568820409f8fdd60",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02136d7250568820409f8fdd60",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851136d7250568820409f8fdd60",
							"width": 64
						}
					],
					"name": "Greatest Hits",
					"release_date": "2009-11-03",
					"release_date_precision": "day",
					"total_tracks": 16,
					"type": "album",
					"uri": "spotify:album:1zCNrbPpz5OLSr6mSpPdKm"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/7jy3rLJdDQY21OgRLCZ9sD"
						},
						"href": "https://api.spotify.com/v1/artists/7jy3rLJdDQY21OgRLCZ9sD",
						"id": "7jy3rLJdDQY21OgRLCZ9sD",
						"name": "Foo Fighters",
						"type": "artist",
						"uri": "spotify:artist:7jy3rLJdDQY21OgRLCZ9sD"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 267360,
				"explicit": false,
				"external_ids": {
					"isrc": "USRW30700007"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/6HNruFQlzQx4ulL4ppRLYI"
				},
				"href": "https://api.spotify.com/v1/tracks/6HNruFQlzQx4ulL4ppRLYI",
				"id": "6HNruFQlzQx4ulL4ppRLYI",
				"is_local": false,
				"name": "The Pretender",
				"popularity": 56,
				"preview_url": "https://p.scdn.co/mp3-preview/4b010601616c61e01d29a3730b9f7099a93eb34f?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 4,
				"type": "track",
				"uri": "spotify:track:6HNruFQlzQx4ulL4ppRLYI"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/4AXpdpyOnye51mlXxsKESw"
							},
							"href": "https://api.spotify.com/v1/artists/4AXpdpyOnye51mlXxsKESw",
							"id": "4AXpdpyOnye51mlXxsKESw",
							"name": "'T Hof Van Commerce",
							"type": "artist",
							"uri": "spotify:artist:4AXpdpyOnye51mlXxsKESw"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/4qakoSUfuux35Kun1m3g93"
					},
					"href": "https://api.spotify.com/v1/albums/4qakoSUfuux35Kun1m3g93",
					"id": "4qakoSUfuux35Kun1m3g93",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273ba53763a1cfeaa26907787c6",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02ba53763a1cfeaa26907787c6",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851ba53763a1cfeaa26907787c6",
							"width": 64
						}
					],
					"name": "Rocky 7",
					"release_date": "2002-10-31",
					"release_date_precision": "day",
					"total_tracks": 15,
					"type": "album",
					"uri": "spotify:album:4qakoSUfuux35Kun1m3g93"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4AXpdpyOnye51mlXxsKESw"
						},
						"href": "https://api.spotify.com/v1/artists/4AXpdpyOnye51mlXxsKESw",
						"id": "4AXpdpyOnye51mlXxsKESw",
						"name": "'T Hof Van Commerce",
						"type": "artist",
						"uri": "spotify:artist:4AXpdpyOnye51mlXxsKESw"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 218200,
				"explicit": false,
				"external_ids": {
					"isrc": "BEY440610021"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/11GmTvbSK704wHxj1a1Nxp"
				},
				"href": "https://api.spotify.com/v1/tracks/11GmTvbSK704wHxj1a1Nxp",
				"id": "11GmTvbSK704wHxj1a1Nxp",
				"is_local": false,
				"name": "Kom Mor Ip",
				"popularity": 33,
				"preview_url": "https://p.scdn.co/mp3-preview/910b9b7e22388c2ffbd42c9e80f4e841e54f8ffd?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 2,
				"type": "track",
				"uri": "spotify:track:11GmTvbSK704wHxj1a1Nxp"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/5QBC8a2fbTyXO8ZkuItG4Z"
							},
							"href": "https://api.spotify.com/v1/artists/5QBC8a2fbTyXO8ZkuItG4Z",
							"id": "5QBC8a2fbTyXO8ZkuItG4Z",
							"name": "Daens, de musical",
							"type": "artist",
							"uri": "spotify:artist:5QBC8a2fbTyXO8ZkuItG4Z"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/41NDf7V5paiYVaBPwx8ECD"
					},
					"href": "https://api.spotify.com/v1/albums/41NDf7V5paiYVaBPwx8ECD",
					"id": "41NDf7V5paiYVaBPwx8ECD",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273975a679f33999271adf43dba",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02975a679f33999271adf43dba",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851975a679f33999271adf43dba",
							"width": 64
						}
					],
					"name": "Daens, de musical",
					"release_date": "2020-02-21",
					"release_date_precision": "day",
					"total_tracks": 28,
					"type": "album",
					"uri": "spotify:album:41NDf7V5paiYVaBPwx8ECD"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/5QBC8a2fbTyXO8ZkuItG4Z"
						},
						"href": "https://api.spotify.com/v1/artists/5QBC8a2fbTyXO8ZkuItG4Z",
						"id": "5QBC8a2fbTyXO8ZkuItG4Z",
						"name": "Daens, de musical",
						"type": "artist",
						"uri": "spotify:artist:5QBC8a2fbTyXO8ZkuItG4Z"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 361602,
				"explicit": false,
				"external_ids": {
					"isrc": "BEY902000015"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/5bo9cWgPmQeKmEvgP1LGsN"
				},
				"href": "https://api.spotify.com/v1/tracks/5bo9cWgPmQeKmEvgP1LGsN",
				"id": "5bo9cWgPmQeKmEvgP1LGsN",
				"is_local": false,
				"name": "De Maat Van Mijn Leven",
				"popularity": 17,
				"preview_url": "https://p.scdn.co/mp3-preview/f0a3a270a3ce2535f3171992124881289aece2de?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 2,
				"type": "track",
				"uri": "spotify:track:5bo9cWgPmQeKmEvgP1LGsN"
			},
			{
				"album": {
					"album_type": "COMPILATION",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
							},
							"href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
							"id": "0LyfQWJT6nXafLPZqxe9Of",
							"name": "Various Artists",
							"type": "artist",
							"uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/0I65T4PBr82AJ5OZUEhmts"
					},
					"href": "https://api.spotify.com/v1/albums/0I65T4PBr82AJ5OZUEhmts",
					"id": "0I65T4PBr82AJ5OZUEhmts",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b27316350574dcf46aba8303209e",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e0216350574dcf46aba8303209e",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d0000485116350574dcf46aba8303209e",
							"width": 64
						}
					],
					"name": "Eurosong For Kids",
					"release_date": "2003",
					"release_date_precision": "year",
					"total_tracks": 11,
					"type": "album",
					"uri": "spotify:album:0I65T4PBr82AJ5OZUEhmts"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/46XJukuDzHoZJczfqphOO8"
						},
						"href": "https://api.spotify.com/v1/artists/46XJukuDzHoZJczfqphOO8",
						"id": "46XJukuDzHoZJczfqphOO8",
						"name": "Martijn",
						"type": "artist",
						"uri": "spotify:artist:46XJukuDzHoZJczfqphOO8"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 178333,
				"explicit": false,
				"external_ids": {
					"isrc": "BEI010312901"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/0rMROmPUMbrMxZyURebYgr"
				},
				"href": "https://api.spotify.com/v1/tracks/0rMROmPUMbrMxZyURebYgr",
				"id": "0rMROmPUMbrMxZyURebYgr",
				"is_local": false,
				"name": "Ik word je pop idool",
				"popularity": 18,
				"preview_url": "https://p.scdn.co/mp3-preview/829f650780b59f5b649e8201d3d0a7e7488b3c0b?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 5,
				"type": "track",
				"uri": "spotify:track:0rMROmPUMbrMxZyURebYgr"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb"
							},
							"href": "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
							"id": "0cmWgDlu9CwTgxPhf403hb",
							"name": "Bonobo",
							"type": "artist",
							"uri": "spotify:artist:0cmWgDlu9CwTgxPhf403hb"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/2T64N96AVfsrRFJCUXQEoZ"
					},
					"href": "https://api.spotify.com/v1/albums/2T64N96AVfsrRFJCUXQEoZ",
					"id": "2T64N96AVfsrRFJCUXQEoZ",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b27355fa09a768d1ef5ea5d279f9",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e0255fa09a768d1ef5ea5d279f9",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d0000485155fa09a768d1ef5ea5d279f9",
							"width": 64
						}
					],
					"name": "Migration",
					"release_date": "2017-01-13",
					"release_date_precision": "day",
					"total_tracks": 12,
					"type": "album",
					"uri": "spotify:album:2T64N96AVfsrRFJCUXQEoZ"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb"
						},
						"href": "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
						"id": "0cmWgDlu9CwTgxPhf403hb",
						"name": "Bonobo",
						"type": "artist",
						"uri": "spotify:artist:0cmWgDlu9CwTgxPhf403hb"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 223720,
				"explicit": false,
				"external_ids": {
					"isrc": "GBCFB1604704"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/16ikmfoT1249gG3pzPvnYt"
				},
				"href": "https://api.spotify.com/v1/tracks/16ikmfoT1249gG3pzPvnYt",
				"id": "16ikmfoT1249gG3pzPvnYt",
				"is_local": false,
				"name": "Second Sun",
				"popularity": 54,
				"preview_url": "https://p.scdn.co/mp3-preview/8fc347f075d26dbc4512dfbb966236b3643a921f?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 5,
				"type": "track",
				"uri": "spotify:track:16ikmfoT1249gG3pzPvnYt"
			},
			{
				"album": {
					"album_type": "SINGLE",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR"
							},
							"href": "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
							"id": "7dGJo4pcD2V6oG8kP0tJRR",
							"name": "Eminem",
							"type": "artist",
							"uri": "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR"
						}
					],
					"available_markets": [
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BR",
						"CH",
						"CL",
						"CO",
						"CR",
						"CZ",
						"DE",
						"DK",
						"EE",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"HK",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JP",
						"LT",
						"LU",
						"LV",
						"MT",
						"MX",
						"MY",
						"NL",
						"NO",
						"NZ",
						"PH",
						"PL",
						"PT",
						"SG",
						"SK",
						"TH",
						"TR",
						"TW",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/1rfORa9iYmocEsnnZGMVC4"
					},
					"href": "https://api.spotify.com/v1/albums/1rfORa9iYmocEsnnZGMVC4",
					"id": "1rfORa9iYmocEsnnZGMVC4",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273b6ef2ebd34efb08cb76f6eec",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02b6ef2ebd34efb08cb76f6eec",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851b6ef2ebd34efb08cb76f6eec",
							"width": 64
						}
					],
					"name": "Just Lose It",
					"release_date": "2004-01-01",
					"release_date_precision": "day",
					"total_tracks": 2,
					"type": "album",
					"uri": "spotify:album:1rfORa9iYmocEsnnZGMVC4"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR"
						},
						"href": "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
						"id": "7dGJo4pcD2V6oG8kP0tJRR",
						"name": "Eminem",
						"type": "artist",
						"uri": "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR"
					}
				],
				"available_markets": [
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BR",
					"CH",
					"CL",
					"CO",
					"CR",
					"CZ",
					"DE",
					"DK",
					"EE",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"HK",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JP",
					"LT",
					"LU",
					"LV",
					"MT",
					"MX",
					"MY",
					"NL",
					"NO",
					"NZ",
					"PH",
					"PL",
					"PT",
					"SG",
					"SK",
					"TH",
					"TR",
					"TW",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 322226,
				"explicit": true,
				"external_ids": {
					"isrc": "USIR10211559"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/1v7L65Lzy0j0vdpRjJewt1"
				},
				"href": "https://api.spotify.com/v1/tracks/1v7L65Lzy0j0vdpRjJewt1",
				"id": "1v7L65Lzy0j0vdpRjJewt1",
				"is_local": false,
				"name": "Lose Yourself - From \"8 Mile\" Soundtrack",
				"popularity": 76,
				"preview_url": null,
				"track_number": 2,
				"type": "track",
				"uri": "spotify:track:1v7L65Lzy0j0vdpRjJewt1"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb"
							},
							"href": "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
							"id": "0cmWgDlu9CwTgxPhf403hb",
							"name": "Bonobo",
							"type": "artist",
							"uri": "spotify:artist:0cmWgDlu9CwTgxPhf403hb"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/2T64N96AVfsrRFJCUXQEoZ"
					},
					"href": "https://api.spotify.com/v1/albums/2T64N96AVfsrRFJCUXQEoZ",
					"id": "2T64N96AVfsrRFJCUXQEoZ",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b27355fa09a768d1ef5ea5d279f9",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e0255fa09a768d1ef5ea5d279f9",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d0000485155fa09a768d1ef5ea5d279f9",
							"width": 64
						}
					],
					"name": "Migration",
					"release_date": "2017-01-13",
					"release_date_precision": "day",
					"total_tracks": 12,
					"type": "album",
					"uri": "spotify:album:2T64N96AVfsrRFJCUXQEoZ"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb"
						},
						"href": "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
						"id": "0cmWgDlu9CwTgxPhf403hb",
						"name": "Bonobo",
						"type": "artist",
						"uri": "spotify:artist:0cmWgDlu9CwTgxPhf403hb"
					},
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/2AcUPzkVWo81vumdzeLLRN"
						},
						"href": "https://api.spotify.com/v1/artists/2AcUPzkVWo81vumdzeLLRN",
						"id": "2AcUPzkVWo81vumdzeLLRN",
						"name": "Rhye",
						"type": "artist",
						"uri": "spotify:artist:2AcUPzkVWo81vumdzeLLRN"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 274693,
				"explicit": false,
				"external_ids": {
					"isrc": "GBCFB1604701"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/2pYvd6cHcAIMAM6xMD6nok"
				},
				"href": "https://api.spotify.com/v1/tracks/2pYvd6cHcAIMAM6xMD6nok",
				"id": "2pYvd6cHcAIMAM6xMD6nok",
				"is_local": false,
				"name": "Break Apart",
				"popularity": 59,
				"preview_url": "https://p.scdn.co/mp3-preview/b8f12939a8f1d238a0b0eaac7263e8ff1c09fdc8?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 2,
				"type": "track",
				"uri": "spotify:track:2pYvd6cHcAIMAM6xMD6nok"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb"
							},
							"href": "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
							"id": "0cmWgDlu9CwTgxPhf403hb",
							"name": "Bonobo",
							"type": "artist",
							"uri": "spotify:artist:0cmWgDlu9CwTgxPhf403hb"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/2T64N96AVfsrRFJCUXQEoZ"
					},
					"href": "https://api.spotify.com/v1/albums/2T64N96AVfsrRFJCUXQEoZ",
					"id": "2T64N96AVfsrRFJCUXQEoZ",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b27355fa09a768d1ef5ea5d279f9",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e0255fa09a768d1ef5ea5d279f9",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d0000485155fa09a768d1ef5ea5d279f9",
							"width": 64
						}
					],
					"name": "Migration",
					"release_date": "2017-01-13",
					"release_date_precision": "day",
					"total_tracks": 12,
					"type": "album",
					"uri": "spotify:album:2T64N96AVfsrRFJCUXQEoZ"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb"
						},
						"href": "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
						"id": "0cmWgDlu9CwTgxPhf403hb",
						"name": "Bonobo",
						"type": "artist",
						"uri": "spotify:artist:0cmWgDlu9CwTgxPhf403hb"
					},
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/2Q0MyH5YMI5HPQjFjlq5g3"
						},
						"href": "https://api.spotify.com/v1/artists/2Q0MyH5YMI5HPQjFjlq5g3",
						"id": "2Q0MyH5YMI5HPQjFjlq5g3",
						"name": "Nick Murphy",
						"type": "artist",
						"uri": "spotify:artist:2Q0MyH5YMI5HPQjFjlq5g3"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 448983,
				"explicit": false,
				"external_ids": {
					"isrc": "GBCFB1604708"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/3aWPdd6U1xbsIEGEpUaPyQ"
				},
				"href": "https://api.spotify.com/v1/tracks/3aWPdd6U1xbsIEGEpUaPyQ",
				"id": "3aWPdd6U1xbsIEGEpUaPyQ",
				"is_local": false,
				"name": "No Reason",
				"popularity": 53,
				"preview_url": "https://p.scdn.co/mp3-preview/58556b15c9c2bdff96995409e98cd95ce8ef2ad7?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 10,
				"type": "track",
				"uri": "spotify:track:3aWPdd6U1xbsIEGEpUaPyQ"
			},
			{
				"album": {
					"album_type": "ALBUM",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
							},
							"href": "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
							"id": "0L8ExT028jH3ddEcZwqJJ5",
							"name": "Red Hot Chili Peppers",
							"type": "artist",
							"uri": "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"JP",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/30Perjew8HyGkdSmqguYyg"
					},
					"href": "https://api.spotify.com/v1/albums/30Perjew8HyGkdSmqguYyg",
					"id": "30Perjew8HyGkdSmqguYyg",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273153d79816d853f2694b2cc70",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02153d79816d853f2694b2cc70",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851153d79816d853f2694b2cc70",
							"width": 64
						}
					],
					"name": "Blood Sugar Sex Magik (Deluxe Edition)",
					"release_date": "1991-09-24",
					"release_date_precision": "day",
					"total_tracks": 19,
					"type": "album",
					"uri": "spotify:album:30Perjew8HyGkdSmqguYyg"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
						},
						"href": "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
						"id": "0L8ExT028jH3ddEcZwqJJ5",
						"name": "Red Hot Chili Peppers",
						"type": "artist",
						"uri": "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 264306,
				"explicit": false,
				"external_ids": {
					"isrc": "USWB19901576"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/3d9DChrdc6BOeFsbrZ3Is0"
				},
				"href": "https://api.spotify.com/v1/tracks/3d9DChrdc6BOeFsbrZ3Is0",
				"id": "3d9DChrdc6BOeFsbrZ3Is0",
				"is_local": false,
				"name": "Under the Bridge",
				"popularity": 81,
				"preview_url": "https://p.scdn.co/mp3-preview/90e41778392f27b6f7dd82db4c90916b3727aa6a?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 11,
				"type": "track",
				"uri": "spotify:track:3d9DChrdc6BOeFsbrZ3Is0"
			},
			{
				"album": {
					"album_type": "SINGLE",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb"
							},
							"href": "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
							"id": "0cmWgDlu9CwTgxPhf403hb",
							"name": "Bonobo",
							"type": "artist",
							"uri": "spotify:artist:0cmWgDlu9CwTgxPhf403hb"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AR",
						"AT",
						"AU",
						"BE",
						"BG",
						"BH",
						"BO",
						"BR",
						"CA",
						"CH",
						"CL",
						"CO",
						"CR",
						"CY",
						"CZ",
						"DE",
						"DK",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FR",
						"GB",
						"GR",
						"GT",
						"HK",
						"HN",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IS",
						"IT",
						"JO",
						"KW",
						"LB",
						"LI",
						"LT",
						"LU",
						"LV",
						"MA",
						"MC",
						"MT",
						"MX",
						"MY",
						"NI",
						"NL",
						"NO",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PH",
						"PL",
						"PS",
						"PT",
						"PY",
						"QA",
						"RO",
						"SA",
						"SE",
						"SG",
						"SK",
						"SV",
						"TH",
						"TN",
						"TR",
						"TW",
						"US",
						"UY",
						"VN",
						"ZA"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/6Eb3lH04iEMK0YJ8gk01MR"
					},
					"href": "https://api.spotify.com/v1/albums/6Eb3lH04iEMK0YJ8gk01MR",
					"id": "6Eb3lH04iEMK0YJ8gk01MR",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b2730e598fe2f3560309382942bb",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e020e598fe2f3560309382942bb",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d000048510e598fe2f3560309382942bb",
							"width": 64
						}
					],
					"name": "Linked",
					"release_date": "2019-07-01",
					"release_date_precision": "day",
					"total_tracks": 1,
					"type": "album",
					"uri": "spotify:album:6Eb3lH04iEMK0YJ8gk01MR"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb"
						},
						"href": "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
						"id": "0cmWgDlu9CwTgxPhf403hb",
						"name": "Bonobo",
						"type": "artist",
						"uri": "spotify:artist:0cmWgDlu9CwTgxPhf403hb"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"disc_number": 1,
				"duration_ms": 369461,
				"explicit": false,
				"external_ids": {
					"isrc": "GBCFB1900100"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/3rCtueI7qBN2kZBZnXuk5K"
				},
				"href": "https://api.spotify.com/v1/tracks/3rCtueI7qBN2kZBZnXuk5K",
				"id": "3rCtueI7qBN2kZBZnXuk5K",
				"is_local": false,
				"name": "Linked",
				"popularity": 62,
				"preview_url": "https://p.scdn.co/mp3-preview/a5edf2b1a999be17263c35ea296cb41d2b72ad25?cid=ec702ad09c13419c944c88121847a2f6",
				"track_number": 1,
				"type": "track",
				"uri": "spotify:track:3rCtueI7qBN2kZBZnXuk5K"
			}
		]
		const indexTopSong = version -1;
		return topSongList[indexTopSong]
	}
	
	
}

export async function getSpotifyId(accessToken) {
	const topLink = [
		"https://api.spotify.com/v1/me"
	].join('');
	const AuthStr = 'Bearer ' + accessToken;
	const res = await axios.get(topLink, { 'headers': { 'Authorization': AuthStr } })
	return res.data.id
}

export async function addPlaylist(name, spotifyId, accessToken) {
	const data = {
		name: name,
		public: false
	};
	const request = [
		"https://api.spotify.com/v1/users/",
		`${spotifyId}`,
		`/playlists`,
	].join('');
	const AuthStr = 'Bearer ' + accessToken;
	const res = await axios.post(request, data, { 'headers': { 'Authorization': AuthStr } });
	return res.data.id
	
}

export async function addSongsToPlaylist(playlistId, tracks, accessToken) {
	const data = {
		uris: tracks,
	};
	const request = [
		"https://api.spotify.com/v1/playlists/",
		`${playlistId}`,
		`/tracks`,
	].join('');
	const AuthStr = 'Bearer ' + accessToken;
	const res = await axios.post(request, data, { 'headers': { 'Authorization': AuthStr } });
	return res
}